name: Request For Comment
description: Request a change to a certain major portion of the project, or to a sub-porject
title: "[RFC]: "
labels: rfc
assignees:
  - SomethingGeneric
  - not-my-segfault
  - hericiumvevo
  - axtloss
  - orowith2os
  - kketg
  - schmoolcool

body:
  - type: input
    id: date-proposed
    attributes:
      label: Date proposed
      placeholder: mm/dd/yyyy
    validations:
      required: true
  - type: input
    id: merge-request
    attributes:
      label: Link to merge request if applicable
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Short summary
      description: A short summary or what you'd like to be changed/improved
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Does this issue/direction affect you directly? Or is it a wider known pain-point. The more niche this is, the more you may have to write here.
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: To consider this RFC complete, what would have to be done?
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks
      description: Is this a trade-off of some kind? List any possible relecant notes here
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there other approaches that could be taken instead? If so, list them here.
    validations:
      required: true
  - type: textarea
    id: unanswered-questions
    attributes:
      label: Unanswered questions
      description: Is there anything that oculd change another part of this RFC, and if so, who might be able to answer them for you?
    validations:
      required: true
